OBJS = main6.c
OBJS2 = status.c

OB_NAME = learnC6SDL

all : $(OBJS) 
	gcc $(OBJS) $(OBJS2) -I C:\Users\Administrator\Desktop\GitHub\SDL2_MinGW_32Bit\include -L C:\Users\Administrator\Desktop\GitHub\SDL2_MinGW_32Bit\lib -lSDL2main -lSDL2 -lSDL2_image -lSDL2_ttf -lSDL2_mixer -o $(OB_NAME)