OBJS = main6.c

OB_NAME = learnC6SDL

all : $(OBJS) 
	gcc $(OBJS) -I C:\Users\Administrator\Desktop\GitHub\SDL2_MinGW_32Bit\include -L C:\Users\Administrator\Desktop\GitHub\SDL2_MinGW_32Bit\lib -lSDL2main -lSDL2 -lSDL2_image -o $(OB_NAME)