print("Witaj, świecie!")
# print("Witaj ponownie")
# print("Podoba mi się takie wpisywanie.")
# print("To jest fajne.")
# print('Jejku! Drukuje.')
# print("Wolałbym, żebyś tego 'nie robił'.")
# print('"Powiedziałem", że masz tego nie dotykać.')
# print('Kolejna linia tekstu.')