OBJS = main5A.cpp
OBJS2 = BouncyBall.cpp
OBJS3 = GameObject.cpp
OBJS4 = Plane.cpp
OBJS5 = TextureManager.cpp

OB_NAME = learnCPP5

all : $(OBJS) 
	g++ $(OBJS) $(OBJS2) $(OBJS3) $(OBJS4) $(OBJS5) -I C:\Users\Administrator\Desktop\GitHub\SDL2_MinGW_32Bit\include -L C:\Users\Administrator\Desktop\GitHub\SDL2_MinGW_32Bit\lib -lSDL2main -lSDL2 -lSDL2_image -o $(OB_NAME)