OBJS = main5A.cpp
OBJS2 = BouncyBall.cpp

OB_NAME = learnCPP5

all : $(OBJS) 
	g++ $(OBJS) $(OBJS2) -I C:\Users\Administrator\Desktop\GitHub\SDL2_MinGW_32Bit\include -L C:\Users\Administrator\Desktop\GitHub\SDL2_MinGW_32Bit\lib -lSDL2main -lSDL2 -lSDL2_image -o $(OB_NAME)